import localFont from "next/font/local";
import "./globals.css";
import { Nunito } from 'next/font/google'
import Footer from "@/components/Footer"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const geistNunito = Nunito({
  subsets: ['latin'], 
  weight: ['300', '400', '600', '700', '800'],  // Pilih variasi berat font
  variable: '--font-nunito',  // Gunakan CSS variable untuk Nunito
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${geistNunito.variable} antialiased`}
      >
       
       {children}
       <Footer/>  
      </body>
      
      
    </html>
  );
}
